---
services:
  registrysvc:
    image: registry:3
    container_name: registry
    ports:
      - 5000:5000
    volumes:
      - registry_data:/var/lib/registry
    networks:
      registrynet:
    restart: unless-stopped

volumes:
  registry_data:

networks:
  registrynet:
    driver_opts:
      com.docker.network.bridge.name: registrynet0
